import { BUILDINGS, TOOL_NAMES } from '../game/constants.js';
import { constructBuilding, inspectProjection, sendAuthorizationRequest, sendReport, queueLocalCargo, queueLocalRoad, queueLocalRobotMove, queueLocalSurvey, assignRobots, scheduleMaintenance } from '../game/engine.js';
import { copyGame, markRevision } from '../game/state.js';
import { powerSources, gridConsumers } from '../game/networks.js';

const schema = (properties, required = []) => ({ type: 'object', properties, required, additionalProperties: false });
const ok = (state, result) => ({ ok: true, sessionId: state.sessionId, revision: state.revision, localDay: state.localDay, result });
const fail = (state, code, message, nextActions = []) => ({ ok: false, sessionId: state.sessionId, revision: state.revision, localDay: state.localDay, error: { code, message, recoverable: true }, nextActions });
// At the readable default playback speed, the 4.37-year one-way courier takes
// roughly 160 seconds of real time. A two-minute lease could therefore expire
// before Daneel had any chance to read the first Earth directive. This is a
// control lease (not in-world signal delay), so it must safely outlast a full
// observe → intent-arrival → acknowledge loop.
export const STEWARD_LEASE_MS = 10 * 60 * 1000;
// The day-zero charter says what the colony is for, not which plan Daneel may
// begin. Local intervention needs a real Earth intent that has crossed the
// gap and has been acknowledged through yield_control. This keeps connection
// from silently turning into autonomous construction.
const hasAcknowledgedEarthDirective = (state) => (state.inbox || []).some((message) => (
  message.handled && message.kind === 'intent'
));

export function createToolSet(store) {
  const get = () => store.getState();
  const guard = (args, write = false) => {
    const state = get();
    if (!state) return fail({ sessionId: 'none', revision: 0, localDay: 0 }, 'STALE_SESSION', 'No committed world.');
    if (args.sessionId !== state.sessionId) return { error: fail(state, 'STALE_SESSION', 'This URL names a different session; reconnect to the current one.') };
    if (write && (!args.leaseId || args.leaseId !== state.connection.leaseId || Date.now() > state.connection.expiresAt)) return { error: fail(state, 'LEASE_EXPIRED', 'The writer lease is missing, expired, or belongs to a reset session.', ['connect_steward']) };
    if (write && state.connection.status !== 'connected') return { error: fail(state, 'NOT_CONNECTED', 'No active steward lease.', ['connect_steward']) };
    return { state };
  };
  const write = (args, fn, { requiresDirective = false } = {}) => {
    const g = guard(args, true); if (g.error) return g.error;
    const state = g.state;
    if (args.expectedRevision !== state.revision) return fail(state, 'STALE_REVISION', 'The committed world changed; inspect again.', ['inspect_colony']);
    if (!args.operationId) return fail(state, 'MISSING_OPERATION_ID', 'Writes require an idempotency key.');
    if (state.receipts[args.operationId]) return state.receipts[args.operationId].result;
    if (requiresDirective && !hasAcknowledgedEarthDirective(state)) {
      return fail(state, 'AWAITING_EARTH_DIRECTIVE', 'Daneel may inspect, report, and protect the relay, but may not begin local work until an Earth intent has arrived and been acknowledged.', ['read_inbox', 'yield_control']);
    }
    try { const next = fn(state); const result = ok(next, { operationId: args.operationId }); next.receipts[args.operationId] = { args, result }; store.commit(next); return result; } catch (e) { return fail(state, e.code || e.message, e.message || 'Action rejected.'); }
  };
  const definitions = [
    { name: 'connect_steward', description: 'Connect Daneel to one saved colony session and acquire its expiring writer lease.', inputSchema: schema({ sessionId: { type: 'string' }, protocolVersion: { type: 'string' }, agentLabel: { type: 'string' } }, ['sessionId', 'protocolVersion']), annotations: { readOnlyHint: false }, execute: async ({ sessionId, protocolVersion, agentLabel = 'Daneel' }) => { const state = get(); if (sessionId !== state.sessionId) return fail(state, 'STALE_SESSION', 'This URL names a different session.'); if (protocolVersion !== 'v1') return fail(state, 'UNKNOWN_PROTOCOL', 'Expected protocol v1.'); if (state.connection.status === 'connected' && state.connection.expiresAt > Date.now()) return fail(state, 'LEASE_HELD', 'Another Daneel lease is active.'); const next = copyGame(state); next.connection = { status: 'connected', leaseId: `lease-${Math.random().toString(36).slice(2)}`, expiresAt: Date.now() + STEWARD_LEASE_MS, agentLabel }; next.paused = false; next.demoPace = true; next.timeScale = [1, 2, 5, 10].includes(next.timeScale) ? next.timeScale : 1; store.commit(markRevision(next)); return ok(next, { leaseId: next.connection.leaseId, tools: TOOL_NAMES, bootstrap: 'Local clock running at 1×. Inspect the charter and inbox, send a connection report if useful, then await an Earth intent before beginning local work.' }); } },
    { name: 'read_inbox', description: 'Read only messages whose lightspeed arrival has occurred. Reading does not acknowledge them.', inputSchema: schema({ sessionId: { type: 'string' }, leaseId: { type: 'string' }, cursor: { type: 'integer', minimum: 0 }, limit: { type: 'integer', minimum: 1, maximum: 20 } }, ['sessionId', 'leaseId']), annotations: { readOnlyHint: true }, execute: async (args) => { const g = guard(args); if (g.error) return g.error; const { state } = g; const cursor = args.cursor || 0; const items = state.inbox.slice(cursor, cursor + (args.limit || 20)); return ok(state, { items, nextCursor: cursor + items.length, hasMore: cursor + items.length < state.inbox.length }); } },
    { name: 'inspect_colony', description: 'Inspect current local colony state available to Daneel.', inputSchema: schema({ sessionId: { type: 'string' }, leaseId: { type: 'string' } }, ['sessionId', 'leaseId']), annotations: { readOnlyHint: true }, execute: async (args) => { const g = guard(args); if (g.error) return g.error; return ok(g.state, inspectProjection(get())); } },
    { name: 'read_doctrine', description: 'Read the delivered authority envelope and protocol definitions.', inputSchema: schema({ sessionId: { type: 'string' }, leaseId: { type: 'string' } }, ['sessionId', 'leaseId']), annotations: { readOnlyHint: true }, execute: async (args) => { const g = guard(args); if (g.error) return g.error; return ok(g.state, get().doctrine); } },
    { name: 'construct_building', description: 'Schedule a costed local construction job on a surveyed safe tile after an acknowledged Earth intent.', inputSchema: schema({ sessionId: { type: 'string' }, leaseId: { type: 'string' }, expectedRevision: { type: 'integer' }, operationId: { type: 'string' }, type: { type: 'string', enum: Object.keys(BUILDINGS) }, x: { type: 'integer' }, y: { type: 'integer' } }, ['sessionId', 'leaseId', 'expectedRevision', 'operationId', 'type', 'x', 'y']), annotations: { readOnlyHint: false, destructiveHint: false }, execute: async (args) => write(args, (state) => constructBuilding(state, args.type, args.x, args.y, 'daneel'), { requiresDirective: true }) },
    { name: 'send_report', description: 'Queue a concise downlink report; Earth receives it after the one-way delay. Include declaredFocus only when you want Earth to learn the bounded focus you chose after an acknowledged directive.', inputSchema: schema({ sessionId: { type: 'string' }, leaseId: { type: 'string' }, expectedRevision: { type: 'integer' }, operationId: { type: 'string' }, text: { type: 'string', maxLength: 1200 }, kind: { type: 'string' }, declaredFocus: { type: 'string', maxLength: 180 } }, ['sessionId', 'leaseId', 'expectedRevision', 'operationId', 'text']), annotations: { readOnlyHint: false }, execute: async (args) => write(args, (state) => sendReport(state, args.text, args.kind || 'status', args.declaredFocus || null)) },
    { name: 'yield_control', description: 'Commit handled delivered messages and release Daneel’s decision checkpoint.', inputSchema: schema({ sessionId: { type: 'string' }, leaseId: { type: 'string' }, expectedRevision: { type: 'integer' }, operationId: { type: 'string' }, eventCursor: { type: 'integer' }, handledMessageIds: { type: 'array', items: { type: 'string' } } }, ['sessionId', 'leaseId', 'expectedRevision', 'operationId']), annotations: { readOnlyHint: false }, execute: async (args) => write(args, (state) => { const next = copyGame(state); for (const m of next.inbox) if ((args.handledMessageIds || []).includes(m.id)) m.handled = true; next.pendingDecision = null; next.cursors.event = args.eventCursor || next.cursors.event; return markRevision(next); }) },
    { name: 'wait_for_event', description: 'Wait for a bounded event cursor update; does not advance simulation time.', inputSchema: schema({ sessionId: { type: 'string' }, leaseId: { type: 'string' }, cursor: { type: 'integer' }, timeoutMs: { type: 'integer', minimum: 0, maximum: 20000 } }, ['sessionId', 'leaseId']), annotations: { readOnlyHint: true }, execute: async (args) => { const g = guard(args); if (g.error) return g.error; const { state } = g; const cursor = args.cursor || 0; const events = state.events.filter((e) => e.id > cursor); return ok(state, { events: events.slice(0, 20), cursor: events.length ? events[events.length - 1].id : cursor, timedOut: events.length === 0, timeoutMs: Math.min(20000, args.timeoutMs || 0) }); } },
  ];
  const sessionFields = { sessionId: { type: 'string' }, leaseId: { type: 'string' } };
  const writeFields = { ...sessionFields, expectedRevision: { type: 'integer' }, operationId: { type: 'string' } };
  const coordinate = { type: 'object', properties: { x: { type: 'integer', minimum: 0, maximum: 31 }, y: { type: 'integer', minimum: 0, maximum: 31 } }, required: ['x', 'y'], additionalProperties: false };
  const extras = [
    ['inspect_resource_network', 'Inspect power, water, and food flows with connectivity.', sessionFields, ['sessionId', 'leaseId'], true, async (args) => { const g = guard(args); if (g.error) return g.error; const state = g.state; return ok(state, { power: state.resources.power, capacity: state.resources.powerCapacity, water: state.resources.water, food: state.resources.food, iridium: state.resources.iridium, connectedSources: powerSources(state).length, connectedConsumers: gridConsumers(state).length, reservePercent: state.resources.powerCapacity ? Math.round(state.resources.power / state.resources.powerCapacity * 100) : 0 }); }],
    ['survey_region', 'Schedule a bounded rover survey after an acknowledged Earth intent; discoveries occur only on completion.', { ...writeFields, region: { type: 'string', enum: ['ridge', 'southern-aquifer', 'northern-reach'] } }, ['sessionId', 'leaseId', 'expectedRevision', 'operationId'], false, async (args) => write(args, (s) => queueLocalSurvey(s, args.region || 'ridge'), { requiresDirective: true })],
    ['build_road', 'Schedule a bounded contiguous road along an explicit tile path after an acknowledged Earth intent; every cell must be buildable regolith.', { ...writeFields, path: { type: 'array', minItems: 2, maxItems: 32, items: coordinate } }, ['sessionId', 'leaseId', 'expectedRevision', 'operationId', 'path'], false, async (args) => write(args, (s) => queueLocalRoad(s, args.path), { requiresDirective: true })],
    ['move_robot', 'Schedule one idle rover to travel to a safe local regolith tile after an acknowledged Earth intent.', { ...writeFields, robotId: { type: 'string' }, x: { type: 'integer', minimum: 0, maximum: 31 }, y: { type: 'integer', minimum: 0, maximum: 31 } }, ['sessionId', 'leaseId', 'expectedRevision', 'operationId', 'robotId', 'x', 'y'], false, async (args) => write(args, (s) => queueLocalRobotMove(s, args.robotId, args.x, args.y), { requiresDirective: true })],
    ['assign_robots', 'Assign named idle robots to a waiting construction job after an acknowledged Earth intent. Busy robots are rejected.', { ...writeFields, jobId: { type: 'string' }, robotIds: { type: 'array', minItems: 1, maxItems: 3, items: { type: 'string' } } }, ['sessionId', 'leaseId', 'expectedRevision', 'operationId', 'jobId', 'robotIds'], false, async (args) => write(args, (s) => assignRobots(s, args.jobId, args.robotIds), { requiresDirective: true })],
    ['modify_production', 'Set a bounded production rate for one completed greenhouse, reservoir, or mine after an acknowledged Earth intent.', { ...writeFields, facilityId: { type: 'string' }, rate: { type: 'number', minimum: 0, maximum: 1 } }, ['sessionId', 'leaseId', 'expectedRevision', 'operationId', 'facilityId', 'rate'], false, async (args) => write(args, (s) => {
      const facility = s.buildings.find((building) => building.id === args.facilityId);
      if (!facility || facility.status !== 'complete') throw Object.assign(new Error('FACILITY_UNAVAILABLE'), { code: 'FACILITY_UNAVAILABLE', reason: 'Select a completed local facility.' });
      if (!['greenhouse', 'reservoir', 'mine'].includes(facility.type)) throw Object.assign(new Error('UNMANAGED_FACILITY'), { code: 'UNMANAGED_FACILITY', reason: 'Only greenhouse, reservoir, and mine output can be throttled.' });
      const n = copyGame(s); n.productionRates = { ...(n.productionRates || {}), [args.facilityId]: args.rate };
      n.logs.push({ day: n.localDay, type: 'production', facilityId: args.facilityId, rate: args.rate }); return markRevision(n);
    }, { requiresDirective: true })],
    ['set_power_priority', 'Set an enumerated power priority after an acknowledged Earth intent.', { ...writeFields, priority: { type: 'string', enum: ['life-support', 'food', 'industry', 'balanced'] } }, ['sessionId', 'leaseId', 'expectedRevision', 'operationId', 'priority'], false, async (args) => write(args, (s) => { const n = copyGame(s); n.doctrine.priority = args.priority; return markRevision(n); }, { requiresDirective: true })],
    ['schedule_maintenance', 'Schedule costed facility maintenance with the maintenance drone after an acknowledged Earth intent.', { ...writeFields, facilityId: { type: 'string' } }, ['sessionId', 'leaseId', 'expectedRevision', 'operationId', 'facilityId'], false, async (args) => write(args, (s) => scheduleMaintenance(s, args.facilityId), { requiresDirective: true })],
    ['register_policy', 'Register bounded typed rules, referencing a delivered instruction or a delivered protocol definition.', { ...writeFields, name: { type: 'string', maxLength: 80 }, version: { type: 'integer', minimum: 1 }, rules: { type: 'array', maxItems: 12, items: { type: 'string', maxLength: 240 } }, sourceInstructionId: { type: 'string' } }, ['sessionId', 'leaseId', 'expectedRevision', 'operationId', 'name', 'sourceInstructionId'], false, async (args) => write(args, (s) => { const delivered = s.inbox.some((m) => m.id === args.sourceInstructionId || m.payload?.sourceInstructionId === args.sourceInstructionId); const proto = s.doctrine.protocols.find((x) => x.sourcePacketId === args.sourceInstructionId || x.reference === args.sourceInstructionId); if (!delivered && !proto) throw Object.assign(new Error('CHECKPOINT_CLOSED'), { code: 'CHECKPOINT_CLOSED', reason: 'A policy must reference a delivered instruction or a delivered protocol definition (e.g. RESILIENCE-24/v1).' }); const n = copyGame(s); n.doctrine.protocols.push({ name: args.name, version: args.version || 1, rules: args.rules || [], sourceInstructionId: args.sourceInstructionId, delivered: true, definitionRef: proto?.reference || args.sourceInstructionId }); return markRevision(n); })],
    ['request_authorization', 'Ask Earth for a delayed authority decision; Earth receives the question after D and its answer after another D.', { ...writeFields, question: { type: 'string', minLength: 1, maxLength: 600 }, options: { type: 'array', minItems: 2, maxItems: 5, items: { type: 'string', maxLength: 80 } }, safeDefault: { type: 'string', maxLength: 80 } }, ['sessionId', 'leaseId', 'expectedRevision', 'operationId', 'question'], false, async (args) => write(args, (s) => sendAuthorizationRequest(s, { question: args.question, options: args.options || ['allow', 'deny'], safeDefault: args.safeDefault }))],
    ['launch_cargo', 'Schedule a bounded cargo launch from a complete launch pad under the active doctrine and an acknowledged Earth intent.', { ...writeFields, quantity: { type: 'number', minimum: 1, maximum: 1000 } }, ['sessionId', 'leaseId', 'expectedRevision', 'operationId', 'quantity'], false, async (args) => write(args, (s) => queueLocalCargo(s, args.quantity), { requiresDirective: true })],
  ];
  for (const [name, description, properties, required, readOnlyHint, execute] of extras) definitions.push({ name, description, inputSchema: schema(properties, required), annotations: { readOnlyHint }, execute });
  return definitions;
}
